### ISSUE TITLE
mongodb exited

### ISSUE THREAD

**Issue by yjfcn** [web3labs/epirus-free#34]
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                      PORTS                NAMES
6238d92044dc        nginx:latest                            "/docker-entrypoint.…"   19 hours ago        Up 19 hours                 0.0.0.0:80->80/tcp   epirus-free_nginx_1
17bb4aed8a8e        web3labs/epirus-free-web:latest         "/bin/sh -c ./entryp…"   19 hours ago        Up 19 hours                 3000/tcp             epirus-free_web_1
5ca1dae41b9e        web3labs/epirus-free-ingestion:latest   "/bin/sh -c 'exec ja…"   19 hours ago        Up 19 hours                                      epirus-free_ingestion_1
02c644e86d98        web3labs/epirus-free-api:latest         "/bin/sh -c 'exec ja…"   19 hours ago        Up 19 hours                                      epirus-free_api_1
565cb5b4ad7c        mongo:latest                            "mongod --logpath=/d…"   19 hours ago        Exited (137) 16 hours ago                        epirus-free_mongodb_1

**Comment by yjfcn** [comment]
2020-11-19 02:21:29.373  INFO 1 --- [}-mongodb:27017] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server mongodb:27017

com.mongodb.MongoSocketException: mongodb
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:211) ~[mongodb-driver-core-3.11.2.jar!/:na]
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:75) ~[mongodb-driver-core-3.11.2.jar!/:na]
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[mongodb-driver-core-3.11.2.jar!/:na]
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128) ~[mongodb-driver-core-3.11.2.jar!/:na]
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.11.2.jar!/:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.net.UnknownHostException: mongodb
        at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName0(Unknown Source) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]
        at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:203) ~[mongodb-driver-core-3.11.2.jar!/:na]
        ... 5 common frames omitted

**Comment by SweeXordious** [comment]
Could you give more details so that I can try to reproduce ?

**Comment by yjfcn** [comment]
> Could you give more details so that I can try to reproduce ?

We set the block time to 1 second and the quorum blockchain runs for about one year, now it has more than 16 million blocks.
The mongodb exited after 3 hours running.

**Comment by yjfcn** [comment]
> @yjfcn also, I think you are the one who posted [this](https://github.com/web3labs/epirus-free/issues/32#issuecomment-729519175) ... did you manage to solve that issue ?

not yet

**Comment by WorldChainS** [comment]
@SweeXordious  I am facing an issue of losing old information on Epirus explorer, after it has been running for a while.
For example, I set it up, it starts up with full information and after a day or two it loses old blocks, tokens, transactions, ... In MongoDB the data seems to be deleted.

When I do a new action on the blockchain, that one is visible until some time passes again.

**Comment by SweeXordious** [comment]
> We set the block time to 1 second and the quorum blockchain runs for about one year, now it has more than 16 million blocks.
> The mongodb exited after 3 hours running.

@yjfcn try deleting the `Epirus-db` from mongo and reingest. I have been running the instance for a day and no such behaviour was noticed.

**Comment by SweeXordious** [comment]
> @SweeXordious I am facing an issue of losing old information on Epirus explorer, after it has been running for a while.
> For example, I set it up, it starts up with full information and after a day or two it loses old blocks, tokens, transactions, ... In MongoDB the data seems to be deleted.
> 
> When I do a new action on the blockchain, that one is visible until some time passes again.

Check here https://github.com/web3labs/epirus-free/issues/35

**Comment by yjfcn** [comment]
This is caused by low memory. Process is killed by system.
